models:
  - name: src_claims
    columns:
      - name: AMOUNT_BILLED
        tests:
          - unique
          - not_null
          - accepted_values:
              arguments:
                values: ['312.32']


            